# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='question_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Questions'),
        ),
    ]
