# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20170306_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Answers',
        ),
    ]
