# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20170312_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question_ID',
        ),
        migrations.AddField(
            model_name='users',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
